### ISSUE TITLE
Serve website as https

### ISSUE THREAD

**Issue by moschlar** [TurboGears/tgwebsite#5]
Hi there,

would it be possible to activate https for the TG2 website?
The main reason would be for the download archives, since new versions of pip will warn and deny to download from non-https index urls.

Example:

```
$ travis_retry pip install --download-cache=$HOME/.pip-cache -i http://tg.gy/${TG2_VERSION//./}/ TurboGears2
[...]
Collecting TurboGears2
  DEPRECATION: Failed to find 'TurboGears2' at http://tg.gy/current/turbogears2/. It is suggested to upgrade your index to support normalized names as the name in /simple/{name}.
  This repository located at tg.gy is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host tg.gy'.
  DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
  Could not find any downloads that satisfy the requirement TurboGears2
  No distributions at all found for TurboGears2
```

(https://travis-ci.org/moschlar/SAUCE/jobs/75221597)

Of course I just added the `--trusted-host` parameter for now, but I think that warning is there for a good reason. ;)

Thanks,
Moritz

**Comment by amol-** [comment]
Uhm, I suppose pip requires a valid SSL cert, so we would need to buy a real SSL cert.
As this is something that happens only for TG < 2.3 as since 2.3 private index is not used anymore, I'm not sure it would make sense to invest the money for a version that should see users diminishing.

I'll have a look and see if we can find a solution that is affordable and solves the problem for users.

**Comment by moschlar** [comment]
What about a free one from StartSSL?

**Comment by Cito** [comment]
Or one from https://letsencrypt.org/ if it can wait a few months.

**Comment by OriginalPenguin** [comment]
This would be nice to see happen now...

**Comment by pedersen** [comment]
It took way too long, but it has happened. TurboGears.org is now served via SSL. There might be other issues that happened due to all the migration, but I think I've kept it all in decent shape.
